### PR TITLE
Use swig generated python loader

### LINKED ISSUE #24: AttributeError: 'module' object has no attribute 'PKCS5_SALT_LEN'
Looks like people have filed issues in a bunch of other places, but not with the actual project.  See:

https://github.com/georgebrock/1pass/issues/21
https://bugs.gentoo.org/show_bug.cgi?id=538920

The error is:

$ python -c "import M2Crypto"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "build/bdist.macosx-10.8-x86_64/egg/M2Crypto/__init__.py", line 24, in <module>
  File "build/bdist.macosx-10.8-x86_64/egg/M2Crypto/ASN1.py", line 12, in <module>
  File "build/bdist.macosx-10.8-x86_64/egg/M2Crypto/BIO.py", line 221, in <module>
  File "build/bdist.macosx-10.8-x86_64/egg/M2Crypto/BIO.py", line 227, in CipherStream
AttributeError: 'module' object has no attribute 'PKCS5_SALT_LEN'

$ python
Python 2.7.9 (default, Jan 29 2015, 06:28:46) 
[GCC 4.2.1 Compatible Apple LLVM 5.1 (clang-503.0.40)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import m2
>>> m2.PKCS5_SALT_LEN
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'PKCS5_SALT_LEN'

I verified the 'fix' listed in the Gentoo bug, i.e. using swig 3.0.4 works fine, and 3.0.5 is broken.  My environment was OS X 10.8.5 with M2Crypto-0.22.3.

### PR DESCRIPTION
**Pull request by joejulian**
This fixes the inability to work with swig 3.0.5+

Fixes #24

### CODE REVIEW

**Comment by mcepl** [comment]
Number of fails/errors in the test suite didn't increase (6/16 on my machine), so thank you very much for the contribution!
